/**
 * The row read: the one git process a repository costs, and what its output
 * means.
 *
 *     git --no-optional-locks for-each-ref --include-root-refs \
 *         --format=<REFS_FORMAT> refs/heads/ HEAD
 *
 * That single command answers everything line 1 and line 2 of the row need -
 * which branch HEAD is on, how far it has drifted from its upstream, and the
 * subject, author, hash and date of the commit it points at - plus a count of
 * the local branches, without touching the working tree. The alternative, and
 * what an earlier reading of the plumbing assumed, was two processes: a
 * `status` for HEAD and a `for-each-ref` for the branches. It was rejected
 * because process spawn is the whole budget here. A directory of two hundred
 * repositories pays that cost two hundred times, and the second process buys
 * nothing this command does not already carry.
 *
 * Both halves of the invocation are load-bearing, and each was verified to fail
 * silently without the other:
 *
 * - `HEAD` as a bare pattern *without* `--include-root-refs` matches nothing and
 *   exits 0. The repository would appear to have no HEAD.
 * - `--include-root-refs` with *no* pattern also lists `refs/remotes/*`,
 *   `refs/tags/*` and the other root refs a repository happens to have -
 *   `ORIG_HEAD` after any reset or merge. On a tag-heavy repository that is
 *   thousands of rows to read and discard, and `ORIG_HEAD` in particular is a
 *   row this parser would have to know to ignore. The two explicit patterns
 *   narrow the root refs to the one that was wanted.
 *
 * `--no-optional-locks` is a git-level option and sits before the subcommand.
 * It is not strictly required for `for-each-ref`, which takes no opportunistic
 * lock, but it is written here anyway because it states the promise the whole
 * extension makes - every command it runs is a read - in the one place a reader
 * checking that promise will look. Placement is the trap: written after the
 * subcommand git exits 129 with ``unknown option `no-optional-locks'``, which
 * for a status read means every repository silently falls into the "did not
 * answer" path.
 */

import type { Divergence, HeadState, LastCommit } from '../model/types.ts';
import { GitMissingError, runGit } from '../util/git.ts';
import { log } from '../util/log.ts';

// ---------------------------------------------------------------------------
// The format
// ---------------------------------------------------------------------------

/**
 * The field separator, as git spells it in a `--format` and as JavaScript
 * spells it in a `split`. They are the same byte, U+001F INFORMATION SEPARATOR
 * ONE, written twice because neither language accepts the other's escape.
 *
 * A vertical bar was the obvious choice and is wrong: commit subjects contain
 * one often enough that the first repository with a `feat(a|b):` subject would
 * shift every field after it. A control character is very much rarer - but it
 * is *not* impossible, which is the finding that shaped the record layout
 * below. `git commit -m $'a\x1fb'` is accepted and the byte survives into
 * `%(contents:subject)` verbatim, as does one in `GIT_AUTHOR_NAME`. So no
 * single-character separator can be trusted to be absent, and the parse cannot
 * rely on the field count alone.
 */
const UNIT_SEPARATOR = '\u001f';
const UNIT_SEPARATOR_FORMAT = '%1f';

/**
 * The fields, in the order the record carries them.
 *
 * The order is a safety property, not a preference. Only the last two fields
 * can contain a separator: a ref name may not contain an ASCII control
 * character (git's own `check-ref-format` refuses one, so `%(refname)` and
 * `%(upstream:short)` are safe), `%(upstream:track)` and
 * `%(upstream:trackshort)` are generated by git from a fixed vocabulary,
 * `%(committerdate:unix)` is digits and `%(objectname:short)` is hex. So the
 * split takes the first eight fields by position and lets the ninth - the
 * subject - absorb every surplus separator, which makes a subject containing
 * one harmless.
 *
 * An author name containing one is *not* harmless: it shifts the boundary
 * between the last two fields, and the row shows a truncated author and a
 * subject with a fragment of the name in front of it. That is the trade
 * deliberately taken. The alternative was to spend a field boundary the other
 * way and let a separator in a subject corrupt the author, and subjects are
 * written by hand thousands of times more often than author names are. Both
 * are cosmetic: neither can turn into a wrong divergence figure, because every
 * field the divergence is computed from sits ahead of the boundary.
 *
 * `%(committerdate:relative)` is deliberately absent. Git localises it, the UI
 * language of this extension is English, and a row reading "vor 3 Tagen" beside
 * an English label is worse than doing the arithmetic here from the unix stamp.
 */
const REFS_FIELDS = [
  '%(HEAD)',
  '%(refname)',
  '%(upstream:short)',
  '%(upstream:track)',
  '%(upstream:trackshort)',
  '%(committerdate:unix)',
  '%(objectname:short)',
  '%(authorname)',
  '%(contents:subject)',
] as const;

export const REFS_FORMAT = REFS_FIELDS.join(UNIT_SEPARATOR_FORMAT);

const FIELD_COUNT = REFS_FIELDS.length;

/**
 * The same four commit fields in `git log`'s spelling, for the one case the
 * legacy fallback cannot answer from refs alone (see `headCommitArgs`).
 */
export const HEAD_COMMIT_FORMAT = ['%ct', '%h', '%an', '%s'].join('%x1f');

const HEADS_PREFIX = 'refs/heads/';

// ---------------------------------------------------------------------------
// The commands
// ---------------------------------------------------------------------------

/**
 * Which shape of read produced a given stdout.
 *
 * The parser has to be told, because the two forms disagree about what an empty
 * answer means: on `root-refs` nothing at all is proof of an unborn repository,
 * while on `heads-only` it is equally consistent with a detached HEAD in a
 * repository that has no branches. Inferring the form from the output would get
 * that exact case wrong, and it is the case where a wrong guess prints "no
 * commits yet" over a repository that has plenty.
 */
export type RefsForm = 'root-refs' | 'heads-only';

export interface RefsCommand {
  readonly args: readonly string[];
  readonly form: RefsForm;
}

/** The one-process read. Needs a git with `--include-root-refs`. */
export function refsArgs(): string[] {
  return [
    '--no-optional-locks',
    'for-each-ref',
    '--include-root-refs',
    `--format=${REFS_FORMAT}`,
    'refs/heads/',
    'HEAD',
  ];
}

/**
 * The same read on a git that has no `--include-root-refs`: local branches
 * only, with `%(HEAD)` still marking the one HEAD points at.
 *
 * That marker is why this form is worth having at all - on a repository that is
 * on a branch, which is nearly all of them, it answers as completely as the
 * one-process form does, and the extra process below is never spawned.
 */
export function legacyRefsArgs(): string[] {
  return ['--no-optional-locks', 'for-each-ref', `--format=${REFS_FORMAT}`, 'refs/heads/'];
}

/**
 * The legacy form's second process, spawned only when no branch row was marked.
 *
 * It exits 0 and prints the branch name for an unborn repository - which is the
 * only way to learn that name, since a repository with no commits has no ref
 * for `for-each-ref` to report at any git version - and exits 1 printing
 * nothing for a detached HEAD. Those two are exactly the cases the marker
 * leaves open, so one command separates them.
 */
export function headSymrefArgs(): string[] {
  return ['--no-optional-locks', 'symbolic-ref', '-q', 'HEAD'];
}

/**
 * The legacy form's third process, spawned only for a detached HEAD on an old
 * git: the commit itself, which no `refs/heads/` row mentions.
 *
 * Three processes for one repository is worse than this project's budget
 * allows, and it is accepted because of how narrow the case is - an old git
 * *and* a detached HEAD - and because the alternative is a row that says
 * "detached" with no commit on it, which is the line the extension exists to
 * show.
 */
export function headCommitArgs(): string[] {
  return [
    '--no-optional-locks',
    'log',
    '--max-count=1',
    `--format=${HEAD_COMMIT_FORMAT}`,
    'HEAD',
  ];
}

// ---------------------------------------------------------------------------
// Capability probe
// ---------------------------------------------------------------------------

let rootRefsSupport: Promise<boolean> | undefined;

/**
 * Whether this git understands `--include-root-refs`. Answered once per
 * session, like `isGitAvailable` in `util/git.ts`.
 *
 * The probe is `git for-each-ref -h`, whose usage text names every option the
 * build supports. Two alternatives were rejected:
 *
 * - Comparing `git --version` against the release that introduced the option.
 *   Distributions backport, vendors append their own suffixes
 *   (`2.39.5 (Apple Git-154)`), and a version comparison that is wrong fails
 *   closed on a git that would have worked, or open on one that will not.
 * - Running the real command and retrying on failure. It works, but it spends
 *   the failure on a repository, and a first pass over a large directory would
 *   pay it once per repository before the answer was cached.
 *
 * `-h` and not `--help`: on Windows `git for-each-ref --help` opens the bundled
 * HTML documentation in the user's browser. `-h` prints usage to stdout, exits
 * 129, and - verified - works outside a repository, which matters because this
 * runs in whatever directory the extension host happens to be in.
 */
export function supportsRootRefs(): Promise<boolean> {
  if (!rootRefsSupport) {
    rootRefsSupport = probeRootRefs();
  }
  return rootRefsSupport;
}

async function probeRootRefs(): Promise<boolean> {
  try {
    const result = await runGit(['for-each-ref', '-h'], {
      cwd: process.cwd(),
      timeoutMs: 5000,
    });
    // The exit code is 129 on success here, because printing usage *is* the
    // failure path of an option parser. Only the text is evidence, so the code
    // is not checked; stderr is searched too, in case some build sends usage
    // there instead.
    const usage = `${result.stdout}\n${result.stderr}`;
    const supported = usage.includes('include-root-refs');
    if (!supported) {
      log.info(
        'this git does not list --include-root-refs, so each repository is read with for-each-ref plus a second command for HEAD',
      );
    }
    return supported;
  } catch (error) {
    if (error instanceof GitMissingError) {
      // Nothing can be read at all; `isGitAvailable` is what says so on the row.
      return false;
    }
    log.warn(`could not probe for --include-root-refs, assuming it is absent: ${String(error)}`);
    return false;
  }
}

/** The read to run, and the form to parse its output as. */
export async function refsCommand(): Promise<RefsCommand> {
  return (await supportsRootRefs())
    ? { args: refsArgs(), form: 'root-refs' }
    : { args: legacyRefsArgs(), form: 'heads-only' };
}

/** Test seam: forget the probed capability, as `resetGitCaches` does for git itself. */
export function resetRefsCapability(): void {
  rootRefsSupport = undefined;
}

// ---------------------------------------------------------------------------
// The parse
// ---------------------------------------------------------------------------

export interface RefsParseOptions {
  /** Which command produced this output. Defaults to the one-process form. */
  readonly form?: RefsForm;
  /** `GitResult.truncated`: output past the byte cap was dropped. */
  readonly truncated?: boolean;
  /**
   * The branch name HEAD would take, for a repository that has no commits.
   *
   * Supplied from `headSymrefArgs` by a caller that has already seen `unborn`
   * come back true and decided the name is worth a second process. Neither form
   * of the read can recover it from its own output: a branch with no commits
   * has no ref, so there is nothing for `for-each-ref` to print at any git
   * version. Without it the row says "no commits yet" and does not say on what,
   * which is true and is most of the value.
   */
  readonly unbornName?: string;
  /**
   * The commit HEAD points at, from `parseHeadCommit`, for the one case a read
   * cannot answer from refs alone: a detached HEAD on a git with no
   * `--include-root-refs`, where there is no `HEAD` row to carry the commit.
   *
   * The caller parses once to discover that case, spends the process, and
   * parses the same output again with this filled in. Re-parsing is a string
   * split over output already in hand, and the alternative - a second entry
   * point that folds the answer into a `RefsRead` after the fact - would put
   * the decision "no marker plus a commit means detached" somewhere other than
   * the one function that makes every other decision about this output.
   */
  readonly headCommit?: LastCommit;
}

/** What one row read established. */
export interface RefsRead {
  readonly head: HeadState;
  readonly divergence: Divergence;
  /** Absent for an unborn repository, and for a HEAD this output did not name. */
  readonly lastCommit?: LastCommit;
  /**
   * Local branches. Undefined rather than zero when the answer was cut short or
   * carried a record this reader could not read: a count nobody established
   * must not render as a number.
   */
  readonly branchCount?: number;
  /**
   * HEAD names a branch that has no commits yet - `git init` and nothing since,
   * or `git checkout --orphan`, which look different in the output and are the
   * same fact.
   *
   * On the one-process form this is read off the absence of the `*` marker and
   * costs nothing. On `heads-only` it is only claimed when `unbornName`
   * confirms it, because there the same absence is equally a detached HEAD.
   *
   * The branch name is a separate question: it is in `head` when the caller
   * paid for `headSymrefArgs`, and `head` is `unknown` when it did not. Whether
   * an unborn repository is worth a second process is the caller's decision -
   * they are rare, so it is cheap in aggregate, and the row reads "no commits
   * yet on gh-pages" instead of "no commits yet".
   */
  readonly unborn: boolean;
  /** Set when part of the answer is missing; the sentence says what and why. */
  readonly incomplete?: string;
}

interface RefRow {
  /** `%(HEAD)` was `*`: this is the ref HEAD points at. */
  readonly current: boolean;
  readonly refname: string;
  readonly upstream: string;
  readonly track: string;
  readonly trackShort: string;
  readonly committedAt: number;
  readonly shortSha: string;
  readonly author: string;
  readonly subject: string;
}

/**
 * Read the output of `refsArgs` or `legacyRefsArgs`.
 *
 * Never throws, and never lets one bad record cost the whole answer: a line
 * that does not have the fields asked for is dropped and reported through
 * `incomplete`, because the useful half of this output is the row HEAD is on
 * and it is worth having even when a branch further down is unreadable.
 */
export function parseRefs(stdout: string, options: RefsParseOptions = {}): RefsRead {
  const form = options.form ?? 'root-refs';
  const rows: RefRow[] = [];
  let malformed = 0;

  for (const line of splitRecords(stdout, options.truncated === true)) {
    const row = splitRecord(line);
    if (row) {
      rows.push(row);
    } else {
      malformed++;
    }
  }

  const incomplete = incompleteReason(options.truncated === true, malformed);
  // A short answer is not a small repository. Both a truncated read and a
  // record this reader could not parse mean branches were seen that were not
  // counted, so the count is withheld rather than reported low.
  const branchCount = incomplete
    ? undefined
    : rows.filter((row) => row.refname.startsWith(HEADS_PREFIX)).length;

  const branch = rows.find((row) => row.current && row.refname.startsWith(HEADS_PREFIX));
  if (branch) {
    return {
      head: { kind: 'branch', name: branch.refname.slice(HEADS_PREFIX.length) },
      divergence: divergenceOf(branch),
      lastCommit: commitOf(branch),
      branchCount,
      unborn: false,
      ...(incomplete ? { incomplete } : {}),
    };
  }

  const detached = rows.find((row) => row.current && row.refname === 'HEAD');
  if (detached) {
    return {
      head: { kind: 'detached', sha: detached.shortSha },
      // Not `unknown`: a detached HEAD has no branch, so it has no
      // `branch.<name>.remote` either and `@{upstream}` errors out. "There is no
      // upstream" is an established fact here rather than an unanswered
      // question, and `view/row.ts` decides whether to say it out loud beside
      // the word "detached" or let the HEAD state speak for both.
      divergence: { kind: 'no-upstream' },
      lastCommit: commitOf(detached),
      branchCount,
      unborn: false,
      ...(incomplete ? { incomplete } : {}),
    };
  }

  // No row carried the marker. What that proves depends on which command ran.
  //
  // On the one-process form it is conclusive, and this was got wrong once: an
  // earlier version claimed unborn only when the output was *empty*, which
  // reads `git init` correctly and reads `git checkout --orphan gh-pages` -
  // where HEAD is equally unborn but every existing branch still prints - as a
  // repository nothing is known about. That is not a corner: an orphan branch
  // is how a docs or pages branch is started. Verified on git 2.52.0.windows.1,
  // the `root-refs` form marks a row in exactly three situations, and they are
  // exhaustive: HEAD is on a branch that exists and that branch row carries the
  // `*`; HEAD is detached and the root `HEAD` row carries it; or HEAD names a
  // branch that does not exist yet, in which case the `HEAD` pattern resolves
  // nothing, no row is printed for it, and no branch row can match. So an
  // unmarked answer here means the third, whether or not other branches printed.
  //
  // On `heads-only` it proves nothing: the command never asks about HEAD, so an
  // unmarked answer is equally a detached HEAD, and claiming unborn would print
  // "no commits yet" over a repository with a decade of them. The caller settles
  // that with `headSymrefArgs` and hands the answer back through `unbornName`.
  const unborn = form === 'root-refs' && !incomplete;
  // A name from `symbolic-ref` is only evidence of an unborn HEAD in company
  // with a complete listing that marked nothing. The command answers with the
  // branch name whether or not that branch has commits, so on an answer that
  // was cut short - where the marked row may be exactly what fell off the end -
  // it says nothing at all, and the row reports what it does not know instead.
  const unbornName = incomplete ? undefined : options.unbornName;
  if (unbornName !== undefined && unbornName.length > 0) {
    return {
      head: { kind: 'unborn', name: shortBranchName(unbornName) },
      // `Divergence.unknown` covers an unborn HEAD by construction: there is no
      // commit, so there is no arithmetic, and `no-upstream` would imply a
      // branch that exists and tracks nothing.
      divergence: { kind: 'unknown' },
      branchCount,
      unborn: true,
      ...(incomplete ? { incomplete } : {}),
    };
  }

  // The legacy detached case, once the caller has spent the third process on it.
  // Guarded by `!unborn` so that a commit handed in by mistake can never turn a
  // repository with no commits into one that has a detached HEAD.
  const headCommit = options.headCommit;
  if (headCommit !== undefined && !unborn) {
    return {
      head: { kind: 'detached', sha: headCommit.shortSha },
      divergence: { kind: 'no-upstream' },
      lastCommit: headCommit,
      branchCount,
      unborn: false,
      ...(incomplete ? { incomplete } : {}),
    };
  }

  return {
    head: { kind: 'unknown' },
    divergence: { kind: 'unknown' },
    branchCount,
    unborn,
    ...(incomplete ? { incomplete } : {}),
  };
}

/**
 * The commit at HEAD from `headCommitArgs`, for the legacy detached case.
 *
 * Undefined rather than a partial commit when the record is not what was asked
 * for: the row can say "detached at <sha>" from the ref read alone, and a
 * commit with a fabricated date would sort the whole list wrongly.
 */
export function parseHeadCommit(stdout: string): LastCommit | undefined {
  const line = stdout.split('\n', 1)[0];
  if (line === undefined) {
    return undefined;
  }
  const parts = stripCarriageReturn(line).split(UNIT_SEPARATOR);
  if (parts.length < 4) {
    return undefined;
  }
  const [committedAt, shortSha, author] = parts;
  if (committedAt === undefined || shortSha === undefined || author === undefined) {
    return undefined;
  }
  if (!isUnixStamp(committedAt) || shortSha.length === 0) {
    return undefined;
  }
  return {
    shortSha,
    committedAt: Number(committedAt),
    subject: parts.slice(3).join(UNIT_SEPARATOR),
    author,
  };
}

// ---------------------------------------------------------------------------
// Records
// ---------------------------------------------------------------------------

/**
 * The output, one record per line.
 *
 * Splitting on the newline is safe in a way splitting on the separator is not:
 * no field in the format can contain one. A ref name may not, an ident may not
 * (git parses the commit header line by line), and `%(contents:subject)` folds
 * a wrapped first paragraph onto one line before printing it - verified against
 * a commit message whose subject ran over two lines.
 *
 * A carriage return, on the other hand, *can* appear inside a subject, so the
 * split is on `\n` alone and only a single trailing `\r` is removed. Stripping
 * every `\r` would silently edit a subject; leaving a trailing one would put a
 * stray glyph on every row if git were ever piped through something that
 * translated line endings.
 */
function splitRecords(stdout: string, truncated: boolean): string[] {
  const lines = stdout.split('\n').filter((line) => line.length > 0);
  // The byte cap cuts wherever it falls, so the last line of a truncated answer
  // is very likely half a record. It is dropped rather than counted as
  // malformed: it is not evidence of anything wrong with the output.
  if (truncated && !stdout.endsWith('\n')) {
    lines.pop();
  }
  return lines;
}

function splitRecord(line: string): RefRow | undefined {
  const parts = stripCarriageReturn(line).split(UNIT_SEPARATOR);
  if (parts.length < FIELD_COUNT) {
    return undefined;
  }
  const marker = parts[0];
  const refname = parts[1];
  const upstream = parts[2];
  const track = parts[3];
  const trackShort = parts[4];
  const committedAt = parts[5];
  const shortSha = parts[6];
  const author = parts[7];
  if (
    marker === undefined ||
    refname === undefined ||
    upstream === undefined ||
    track === undefined ||
    trackShort === undefined ||
    committedAt === undefined ||
    shortSha === undefined ||
    author === undefined
  ) {
    return undefined;
  }
  // A record whose date is not a unix stamp is not this format's output. It is
  // rejected whole rather than kept with a zero date, which would sort the
  // repository to the bottom of a list ordered by last commit and read as a
  // repository that has not moved since 1970.
  if (refname.length === 0 || !isUnixStamp(committedAt)) {
    return undefined;
  }
  return {
    current: marker === '*',
    refname,
    upstream,
    track,
    trackShort,
    committedAt: Number(committedAt),
    shortSha,
    author,
    // Everything past the eighth separator belongs to the subject.
    subject: parts.slice(FIELD_COUNT - 1).join(UNIT_SEPARATOR),
  };
}

function incompleteReason(truncated: boolean, malformed: number): string | undefined {
  if (truncated) {
    return 'The ref listing reached the size limit this reader accepts, so some branches were not read.';
  }
  if (malformed > 0) {
    // "Some of the refs" rather than "the branch count", which is what this
    // said while a dropped record could only cost a count. A dropped record can
    // also be the row HEAD is on, and then the head state and the divergence
    // are missing too - so the sentence names the cause and leaves the reader
    // to see which fields are silent, rather than listing one of three.
    return malformed === 1
      ? 'One line of the ref listing did not carry the fields this read asked for, so some of the refs were not read.'
      : `${malformed} lines of the ref listing did not carry the fields this read asked for, so some of the refs were not read.`;
  }
  return undefined;
}

function isUnixStamp(value: string): boolean {
  return /^\d+$/.test(value);
}

function stripCarriageReturn(line: string): string {
  return line.endsWith('\r') ? line.slice(0, -1) : line;
}

/** `refs/heads/feature/one` -> `feature/one`; anything else is returned as it is. */
function shortBranchName(ref: string): string {
  return ref.startsWith(HEADS_PREFIX) ? ref.slice(HEADS_PREFIX.length) : ref;
}

// ---------------------------------------------------------------------------
// Divergence
// ---------------------------------------------------------------------------

/**
 * Which of the five divergence cases this branch is in.
 *
 * The decision is made from `%(upstream:short)` and `%(upstream:trackshort)`,
 * and only the *magnitudes* are read out of `%(upstream:track)`. That split is
 * the point of this function. `track` is prose - `[ahead 1, behind 1]`,
 * `[gone]` - and prose in git is a candidate for translation, while
 * `trackshort` is punctuation and is not. Whether this particular string is
 * translated could not be settled here: forcing `LC_ALL` to four locales on the
 * development machine changed nothing, which proves only that those message
 * catalogues were not installed. So the words are treated as untrustworthy
 * without a claim that they are wrong - the classification below rests entirely
 * on the two fields that cannot be prose, and the row would survive a git that
 * says `[voraus 1]`:
 *
 *     upstream  trackshort  track                 meaning
 *     (empty)   (empty)     (empty)               the branch tracks nothing
 *     origin/x  =           (empty)               in sync
 *     origin/x  (empty)     [gone]                the upstream ref is gone
 *     origin/x  >           [ahead 1]             ahead only
 *     origin/x  <           [behind 1]            behind only
 *     origin/x  <>          [ahead 1, behind 1]   both
 *
 * Every row of that table was produced from a real repository driven into the
 * state. It is what keeps the three facts the model insists are different -
 * no upstream, upstream gone, in sync - actually distinct here, since all three
 * have an empty `track` and only two of the three fields together separate
 * them.
 */
function divergenceOf(row: RefRow): Divergence {
  if (row.upstream.length === 0) {
    return { kind: 'no-upstream' };
  }
  if (row.trackShort === '=') {
    return { kind: 'in-sync', upstream: row.upstream };
  }
  if (row.trackShort.length === 0) {
    // An upstream with no short marker is git's way of saying the remote-tracking
    // ref has disappeared. `track` is required to be non-empty as well - it holds
    // git's word for it - because without either signal nothing has been
    // established, and "gone" is far too strong a thing to say on a hunch.
    return row.track.length > 0 ? { kind: 'gone', upstream: row.upstream } : { kind: 'unknown' };
  }

  const numbers = row.track.match(/\d+/g)?.map(Number) ?? [];
  if (row.trackShort === '>' && numbers.length === 1) {
    return { kind: 'diverged', upstream: row.upstream, ahead: numbers[0] ?? 0, behind: 0 };
  }
  if (row.trackShort === '<' && numbers.length === 1) {
    return { kind: 'diverged', upstream: row.upstream, ahead: 0, behind: numbers[0] ?? 0 };
  }
  if (row.trackShort === '<>' && numbers.length === 2) {
    // Which number is which. When git's own words are in the string - they are
    // on every English build, which is nearly every build - their order decides
    // it and nothing is assumed. Otherwise the order git writes them in is
    // used, ahead first, which is the single place this parse trusts a layout
    // it cannot see. Getting it wrong swaps two figures on one row; refusing to
    // answer would blank the divergence of every repository on a translated
    // git, which is worse.
    const aheadAt = row.track.indexOf('ahead');
    const behindAt = row.track.indexOf('behind');
    const aheadFirst = aheadAt < 0 || behindAt < 0 || aheadAt < behindAt;
    const first = numbers[0] ?? 0;
    const second = numbers[1] ?? 0;
    return {
      kind: 'diverged',
      upstream: row.upstream,
      ahead: aheadFirst ? first : second,
      behind: aheadFirst ? second : first,
    };
  }

  // A marker with no figure to go with it. The branch has drifted, and by how
  // much is not known - so nothing is claimed, rather than a zero that would
  // read as "in sync".
  return { kind: 'unknown' };
}

function commitOf(row: RefRow): LastCommit {
  return {
    shortSha: row.shortSha,
    committedAt: row.committedAt,
    subject: row.subject,
    author: row.author,
  };
}
